name: dart_coveralls

executables:
  dart_coveralls:

version: 0.0.18
author: Axel Christ <adracus@gmail.com>
description: |-
  Pub package to calculate coverage, format it
  to LCOV and send it to coveralls
homepage: https://github.com/Adracus/dart-coveralls
documentation: https://github.com/Adracus/dart-coveralls
dependencies:
  args: '>=0.12.0+2 <0.13.0'
  coverage: '>=0.5.0 <0.6.0'
  http: '>=0.11.1+1 <0.12.0'
  path: '>=1.3.0 <2.0.0'
  logging: ">=0.9.2 <0.10.0"
  yaml: ">=2.1.2 <3.0.0"
  mockable_filesystem: ">=0.0.3 <0.1.0"
dev_dependencies:
  unittest: ">=0.11.3 <0.12.0"
  mock: ">=0.11.0+2 <0.12.0"
